services:
  web:
    image: ghcr.io/ivanpashkulev/web-main:d4e3b259c78936dc56494d59a44cbbc47d9b9c83
    container_name: web-main
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api

  api:
    image: ghcr.io/ivanpashkulev/api-main:22e611c547551d263ab5c14be93c783d7b154c5e
    container_name: api-main
    restart: unless-stopped
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:?OPENAI_API_KEY is required}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o-mini}
    volumes:
      - ./assets:/app/assets

  dj:
    image: ghcr.io/ivanpashkulev/dj:93fbb061810f2c9299264d03b5e2c93129ca214c
    container_name: dj
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
      - dj
    restart: unless-stopped
