services:
  web:
    image: ghcr.io/ivanpashkulev/web-main:3b25a53
    container_name: web-main
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api

  api:
    image: ghcr.io/ivanpashkulev/api-main:2491fbf
    container_name: api-main
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - ./assets:/app/assets

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
    restart: unless-stopped
