services:
  web:
    image: ghcr.io/ivanpashkulev/web-main:12a251a2fb4fac58d6404316f219a1c2a3870fc0
    container_name: web-main
    restart: unless-stopped
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api

  api:
    image: ghcr.io/ivanpashkulev/api-main:2491fbf
    container_name: api-main
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    volumes:
      - ./assets:/app/assets

  dj:
    image: ghcr.io/ivanpashkulev/dj:afa4ae3
    container_name: dj
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - api
      - dj
    restart: unless-stopped
