name: Hetzner Terraform
description: Set up Terraform, authenticate the state backend and execute Terraform.

inputs:
  action:
    description: Terraform operation, Provision or Destroy.
    required: true
  should_apply:
    description: Whether to apply the generated plan.
    required: true
  terraform_version:
    description: Exact Terraform version.
    required: true
  aws_role_to_assume:
    description: AWS role for accessing Terraform state.
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate AWS state backend
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ inputs.aws_role_to_assume }}
        aws-region: eu-central-1

    - name: Execute Terraform ${{ inputs.action }}
      uses: pashkulev-devops-projects/github-actions/actions/terraform@508d9cc538b84adeb6744dab7b523093db38645b
      with:
        terraform_version: ${{ inputs.terraform_version }}
        working_directory: terraform/hetzner
        action: ${{ inputs.action }}
        should_apply: ${{ inputs.should_apply }}
