ssl_certificate /etc/nginx/ssl/cloudflare-origin.crt;
ssl_certificate_key /etc/nginx/ssl/cloudflare-origin.key;

proxy_set_header Host $host;
proxy_set_header X-Forwarded-Proto $scheme;

server {
    listen 80;
    server_name ivanpashkulev.com dj.ivanpashkulev.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ivanpashkulev.com;

    location /api/ {
        proxy_pass http://api:8000/;
        proxy_buffering off;
    }

    location / {
        proxy_pass http://web:4173;
    }
}

server {
    listen 443 ssl;
    server_name dj.ivanpashkulev.com;

    location / {
        proxy_pass http://dj:3000;
    }
}
