---
collections:
  - name: hetzner.hcloud
    version: "6.10.0"
  - name: community.docker
    version: "5.2.2"
  - name: https://github.com/pashkulev-devops-projects/ansible.git
    type: git
    version: 079c13036287fb4f7766ad30c2686f1ad14c8aab
