---
collections:
  - name: hetzner.hcloud
    version: "6.10.0"
  - name: community.docker
    version: "5.2.2"
  - name: https://github.com/pashkulev-devops-projects/ansible.git
    type: git
    version: 371b155c1d5ac5dd6e82f173131b166864cf00d9
